### ISSUE TITLE
PL translation fix

### ISSUE THREAD

**Issue by zcaalock** [ChobitsCrazy/BetterSorting#18]
Hi, i fixed encoding that did not display polish letters in game.
[IG_UI_PL.txt](https://github.com/ChobitsCrazy/BetterSorting/files/8575289/IG_UI_PL.txt)
[ItemName_PL.txt](https://github.com/ChobitsCrazy/BetterSorting/files/8575290/ItemName_PL.txt)

**Comment by ChobitsCrazy** [comment]
Looks a bit messed up to me, getting things like:
Wygl¹d
Odzie¿
Œmieæ

**Comment by zcaalock** [comment]
You need to look at it in ANSI encoding

**Comment by ChobitsCrazy** [comment]
Yeah it shows encoded as ANSI
![image](https://user-images.githubusercontent.com/21301107/165623609-96550961-821e-4ec5-8c22-0fc37c1089ea.png)

**Comment by zcaalock** [comment]
hmm, it looks good on my computer. Can you check it in game? Or maybe some polish user could do it.
btw i fallowed the translation instruction about foreign symbols i found on the internet.

**Comment by ChobitsCrazy** [comment]
Can you just paste the contents of the file as a comment here instead of uploading as a file? As long as it looks okay I can manually update it.

**Comment by ChobitsCrazy** [comment]
Expired 30 days.
