### ISSUE TITLE
water (including buckets of water etc) are titled IGUI_ItemCat_Drainable

### ISSUE THREAD

**Issue by jinxytaboo** [ChobitsCrazy/BetterSorting#31]

**Comment by Sekket** [comment]
I have the same issue i added new categories for myself and i need help removing "IGUI_ItemCat_" part if possible

**Comment by ChobitsCrazy** [comment]
Not able to recreate this issue. I loaded a new save with just BetterSorting and water bottles, bucket of water, bleach bottle with water are all showing as Food - Beverage.

**Comment by Sekket** [comment]
for myself i reloaded new save with only the BetterSorting on and i have this issue with vests and ammo.. and also when i try to adjust items categories from [Item_Categories] LUA file, i have the same issue [IGUI_ItemCat_] then the name of the category. [https://imgur.com/a/X6kiaZs](url) here's a screenshot..

**Comment by Sekket** [comment]
also i have a question, if i may.. for example in [Item_Categories.LUA] Line TweakItem("Base.HairDyeBlack","DisplayCategory","Appear"); how its written [Appear] while ingame its displayed as [Appearance]

**Comment by Sekket** [comment]
> also i have a question, if i may.. for example in [Item_Categories.LUA] Line TweakItem("Base.HairDyeBlack","DisplayCategory","Appear"); how its written [Appear] while ingame its displayed as [Appearance]

i got my answer after fully ready your mod support document and solved the issue now, category name must be added also in the translate files of BetterSorting mod.
