### ISSUE TITLE
Enquiry: Adding Categories Manually

### ISSUE THREAD

**Issue by Teally** [ChobitsCrazy/BetterSorting#40]
Hello,
sorry for opening this as an issue. I'm a player who gets annoyed that when I loot a zombie for their clothes to rip, I always have to avoid selecting a pair of Shoes that appear in the middle of the list between the clothes I want to tear.
I was planning to add a new category "Clothing - Footwear" by myself to solve my own inconvenience, but I am not familiar with the lua scripts and I decided to reach out for some help.

I am concerned about a few things:

a. if I created a new mod mirroring your structure to add "ClothF", will it conflict with or be overwritten by the current script from your mod when I run both on my server?
I ask this because I see that the mod also tweaks the shoes:
```
TweakItem("Base.Shoes_ArmyBoots","DisplayCategory","Cloth");
```
b. I also browsed `lua\shared\Translate\EN\`. I roughly understood `ItemName_EN.txt`, but in `IG_UI_EN.txt`, I do not understand `IGUI_ItemCat`. How does `TweakItem(itemName, "DisplayCategory", propertyValue)` convert `DisplayCategory = propertyValue = "Cloth"` to `"Clothing"`?
Do I simply add a definition for `"IGUI_ItemCat_ClothF = "Clothing - Footwear"`, and then `TweakItem()` will work with `"ClothF"`?

Again, sorry if this is not a good place to discuss. Any sort of reply will be appreciated!

**Comment by ChobitsCrazy** [comment]
You can do this individually and shouldn't cause a conflict but not within my version scope.
