### ISSUE TITLE
VFE STALKER Expansion

### ISSUE THREAD

**Issue by ilrosso17** [ChobitsCrazy/BetterSorting#46]
Here is my contribution to the mod by adding VFE STALKER Expansion (ID:"VFExpansion2")

The items added by the mod are under the Base module; idk if it should show in my game if I add the strings to the additional mod file but it doesn't show up so I'm pullin the request here. Salute! Ty for the best mod ever.

require("ItemTweaker_Copy_CC");

--VFES
--https://steamcommunity.com/sharedfiles/filedetails/?id=2893333090
if getActivatedMods():contains("VFExpansion2") then
TweakItem("Base.Mosin","DisplayCategory","WepFire");
TweakItem("Base.Saiga12","DisplayCategory","WepFire");
TweakItem("Base.SVD","DisplayCategory","WepFire");
TweakItem("Base.Galil","DisplayCategory","WepFire");
TweakItem("Base.UMP45","DisplayCategory","WepFire");
TweakItem("Base.Makarov","DisplayCategory","WepFire");
TweakItem("Base.USP45","DisplayCategory","WepFire");
TweakItem("Base.SV98","DisplayCategory","WepFire");
TweakItem("Base.M249","DisplayCategory","WepFire");
TweakItem("Base.PKM","DisplayCategory","WepFire");
TweakItem("Base.Vityaz","DisplayCategory","WepFire");
TweakItem("Base.HK416","DisplayCategory","WepFire");
TweakItem("Base.VSS","DisplayCategory","WepFire");
TweakItem("Base.SVT40","DisplayCategory","WepFire");
TweakItem("Base.MP153","DisplayCategory","WepFire");
TweakItem("Base.MP153sawn","DisplayCategory","WepFire");
TweakItem("Base.762Clip10","DisplayCategory","WepAmmoMag");
TweakItem("Base.939Clip10","DisplayCategory","WepAmmoMag");
TweakItem("Base.556box100","DisplayCategory","WepAmmoMag");
TweakItem("Base.762box100","DisplayCategory","WepAmmoMag");
TweakItem("Base.12Clip5","DisplayCategory","WepAmmoMag");
TweakItem("Base.762Clip102","DisplayCategory","WepAmmoMag");
TweakItem("Base.762Clip103","DisplayCategory","WepAmmoMag");
TweakItem("Base.9mmClip8","DisplayCategory","WepAmmoMag");
TweakItem("Base.45Clip12","DisplayCategory","WepAmmoMag");
TweakItem("Base.45Clip25","DisplayCategory","WepAmmoMag");
TweakItem("Base.9mmClip302","DisplayCategory","WepAmmoMag");
end

**Comment by ChobitsCrazy** [comment]
Added
