### ISSUE TITLE
Bourbon water miscategorised as "Food - alcohol"

### ISSUE THREAD

**Issue by kafu0611** [ChobitsCrazy/BetterSorting#58]
As the screenshot shows Bourbon water should be Food - beverage not Food - alcohol
![Snipaste_2023-05-31_22-28-53](https://github.com/ChobitsCrazy/BetterSorting/assets/10711790/251618f4-38e3-4ecd-8b9a-5f33bd4529ca)
![image](https://github.com/ChobitsCrazy/BetterSorting/assets/10711790/e19c5ca8-ed68-4d60-9283-12793d7ab2e1)

**Comment by ChobitsCrazy** [comment]
Thank you, this is fixed for next release.
