### ISSUE TITLE
Update V2.0.1 compatibility issues.

### ISSUE THREAD

**Issue by NeoAnubis7** [ChobitsCrazy/BetterSorting#59]
As of update V2.0.1 (it persists on V2.0.2) many items seem to be miscategorized and some categories appear to no longer exist.

Antibiotics, beverages, alcohols and condiments are now all set as "food - non-perishable", the same happened to bleach (lol), some items that before were categorized as "cooking" (pans and such) are now containers.

The screenshots on the other issue suggests that this issue doesn't affect this mod on it's own, since there are "Food - alcohol" items there and this category seems to no longer exist in my game, indicating that this is a compatibility problem with some other mod.

I can say with certainty that this was technically caused by update V2.0.1 since none of my other mods updated at the same date and nothing else changed.

As a side note - some of the new categories added in the update do exist ingame, like "clothing - arms/hands", so the update did apply.

I am aware that this might not be a problem that can be fixed by the developer of "Better Sorting" but I do want to let you know that compatibility issues now exist - I'm still trying to pinpoint what exactly is the other mod that is now causing it when in combination with this - but since steam discussion seems to be closed this is the only real way to report this.

![PZ](https://github.com/ChobitsCrazy/BetterSorting/assets/96957255/992a6875-b794-4802-a2f2-378533ad330f)

**Comment by NeoAnubis7** [comment]
Through trial and error I was able to pinpoint the mod causing the problem.

It is "The Workshop" by "djvirus" that causes the issue - according to their discord members the problem relates to that mod's item tweaker doing things it shouldn't.

Apparently the issue already existed before this mod's update though so I am unsure as to why for me it only manifested with the update on my end.

**Comment by ChobitsCrazy** [comment]
Well this is good information, thank you for finding this. I'll add a note on my mod page to make sure Better Sorting is loaded last.

**Comment by ChobitsCrazy** [comment]
I also contain my own version of item tweaker.
