### ISSUE TITLE
Is Item Tweaker API a requirement

### ISSUE THREAD

**Issue by Kem984** [ChobitsCrazy/BetterSorting#78]
I tried to use BetterSorting on a local hosted Server ( not dedicated ) and after creating my character i get an error:
File doesn´t exist on server:
media/lua/shared/itemtweaker_copy_cc.lua

So I like to know if item tweaker is needed because its not listed as a dependency.

**Comment by ChthonicKnight** [comment]
Better sorting does not require Item Tweaker we bundle our own version.
