### ISSUE TITLE
Sort by Favorite

### ISSUE THREAD

**Issue by Deliphin** [ChobitsCrazy/BetterSorting#80]
I frequently use the favorites function to make sure I don't accidentally move something I don't want to. But what would be even better is if all my favorites were kept together, so I could easier find the non-favorite stuff in my bags or inventory.

**Comment by ChthonicKnight** [comment]
I do not adjust the functionality of the item viewer in anyway this simply updates the items themselves to show with a better category so you will have to find support for this outside of this mod.
